# Generated by Django 3.1.7 on 2021-04-20 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.CharField(max_length=128, unique=True)),
                ('job_id', models.CharField(max_length=128)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sürekli Görev',
                'verbose_name_plural': 'Sürekli Görevler',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.CharField(max_length=128, unique=True)),
                ('job_id', models.CharField(max_length=128)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tek Seferlik Görev',
                'verbose_name_plural': 'Tek Seferlik Görevler',
            },
        ),
        migrations.CreateModel(
            name='ScheduledTaskInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('scheduled_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TwintSearch.scheduledtask')),
            ],
            options={
                'verbose_name': 'Sürekli Görev',
                'verbose_name_plural': 'Sürekli Görev Instance',
            },
        ),
    ]
